import { LanguageSwitcher } from "@/components/language-switcher"
import { Navigation } from "@/components/navigation"
import { LanguageProvider } from "@/lib/i18n/language-context"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
          <header className="border-b">
            <div className="container mx-auto flex h-16 items-center px-4">
              <div className="mr-8 font-bold text-lg">Ads.txt Manager V2</div>
              <Navigation />
              <div className="ml-auto">
                <LanguageSwitcher />
              </div>
            </div>
          </header>
          <main>{children}</main>
        </LanguageProvider>
      </body>
    </html>
  )
}
